"""empty message
Revision ID: 3682cbecb9ba
Revises: 6a8576ed756a
Create Date: 2021-03-07 16:58:13.284237
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3682cbecb9ba'
down_revision = '6a8576ed756a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###